import type { Metadata } from "next";

import { Poppins } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { ThemeProvider } from "./themeProvider";
import ClientDarkModeToggle from "./ClientDarkModeToggle";

//2.Create a new popiins variable like this
const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "PROMPT PLANNER AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Toaster />
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ClientDarkModeToggle />
          <main className={poppins.variable}>{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
